name: ColorPicker
author:  fcoulter
current:  1.0.0
category: Utilities
tags:  [Colorpicker, color picker]
docs: http://www.spiralscripts.co.uk/demos/colorpicker/how-to-use.html
demo: http://www.spiralscripts.co.uk/demos/colorpicker/demo-1.2.4.html
